package com.nutalig.constant;

public enum ActivityAction {
    CREATE,
    UPDATE,
    DELETE,
    VIEW,
    STATUS_CHANGE,
    REQUEST_INFORMATION,
    ASSIGN_SALES,
    LINK_CUSTOMER,
    UPLOAD_PICTURE,
    DELETE_PICTURE,
    REPLACE_PICTURE,
    REORDER_PICTURE,
    GENERATE_INQUIRY_MESSAGE,
    UPDATE_INQUIRY_MESSAGE,
    GENERATE_MESSAGE,
    RECEIVE_PAYMENT,
    REQUEST_APPROVAL,
    APPROVE,
    REJECT
}
