package com.nutalig.constant;

public enum SystemConstant {
    CONTACT_CHANNEL,
    COST_TYPE,
    CUSTOMER_BILLING_CONDITION,
    CUSTOMER_CREDIT_TERM,
    CUSTOMER_PAYMENT_TERM,
    CUSTOMER_PAYMENT_CYCLE,
    CUSTOMER_TYPE,
    CUSTOMER_TIER,
    CUSTOMER_SEGMENT,
    CURRENCY,
    ORDER_TYPE,
    REPORT_VAT,
    REPORT_NO_VAT,
    RFQ_TYPE,
    SALES_TYPE,
    POSITION,
    TEAM,
    VAT,
    UNIT
}
