CREATE TABLE IF NOT EXISTS invoice (
    invoice_no VARCHAR(50) NOT NULL,
    sales_order_no VARCHAR(50) NOT NULL,
    quotation_no VARCHAR(50) DEFAULT NULL,
    doc_date DATE DEFAULT NULL,
    due_date DATE DEFAULT NULL,
    delivery_date DATE DEFAULT NULL,
    status VARCHAR(30) NOT NULL,
    currency VARCHAR(10) DEFAULT NULL,
    customer_id VARCHAR(255) DEFAULT NULL,
    customer_address_id BIGINT DEFAULT NULL,
    customer_contact_id BIGINT DEFAULT NULL,
    sales_id VARCHAR(255) DEFAULT NULL,
    co_sales_id VARCHAR(20) DEFAULT NULL,
    subtotal DECIMAL(18,2) DEFAULT NULL,
    discount DECIMAL(18,2) DEFAULT NULL,
    freight DECIMAL(18,2) DEFAULT NULL,
    amount DECIMAL(18,2) DEFAULT NULL,
    commission DECIMAL(18,2) DEFAULT NULL,
    vat_rate DECIMAL(6,4) DEFAULT NULL,
    vat DECIMAL(18,2) DEFAULT NULL,
    grand_total DECIMAL(18,2) DEFAULT NULL,
    paid_total DECIMAL(18,2) DEFAULT NULL,
    outstanding_total DECIMAL(18,2) DEFAULT NULL,
    remark VARCHAR(2000) DEFAULT NULL,
    rev_no INT DEFAULT NULL,
    customer_name_snapshot VARCHAR(255) DEFAULT NULL,
    customer_tax_id_snapshot VARCHAR(50) DEFAULT NULL,
    customer_address_snapshot VARCHAR(2000) DEFAULT NULL,
    customer_contact_snapshot VARCHAR(255) DEFAULT NULL,
    customer_phone_snapshot VARCHAR(100) DEFAULT NULL,
    sales_name_snapshot VARCHAR(255) DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (invoice_no),
    KEY idx_invoice_sales_order_no (sales_order_no),
    KEY idx_invoice_quotation_no (quotation_no),
    KEY idx_invoice_doc_date (doc_date),
    KEY idx_invoice_status (status),
    KEY idx_invoice_customer_id (customer_id),
    KEY idx_invoice_sales_id (sales_id),
    CONSTRAINT fk_invoice_sales_order FOREIGN KEY (sales_order_no) REFERENCES sales_order (sales_order_no),
    CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_invoice_customer_address FOREIGN KEY (customer_address_id) REFERENCES customer_address (id),
    CONSTRAINT fk_invoice_customer_contact FOREIGN KEY (customer_contact_id) REFERENCES customer_contact (id),
    CONSTRAINT fk_invoice_sales FOREIGN KEY (sales_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_invoice_created_by FOREIGN KEY (created_by) REFERENCES user (id),
    CONSTRAINT fk_invoice_updated_by FOREIGN KEY (updated_by) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS invoice_detail (
    id BIGINT NOT NULL AUTO_INCREMENT,
    invoice_no VARCHAR(50) NOT NULL,
    sales_order_detail_id BIGINT DEFAULT NULL,
    line_no INT DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    type VARCHAR(255) DEFAULT NULL,
    capacity VARCHAR(255) DEFAULT NULL,
    size VARCHAR(255) DEFAULT NULL,
    spec VARCHAR(2000) DEFAULT NULL,
    unit_price DECIMAL(18,2) DEFAULT NULL,
    quantity DECIMAL(18,2) DEFAULT NULL,
    amount DECIMAL(18,2) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_invoice_detail_invoice_no (invoice_no),
    KEY idx_invoice_detail_sales_order_detail_id (sales_order_detail_id),
    CONSTRAINT fk_invoice_detail_invoice FOREIGN KEY (invoice_no) REFERENCES invoice (invoice_no),
    CONSTRAINT fk_invoice_detail_sales_order_detail FOREIGN KEY (sales_order_detail_id) REFERENCES sales_order_detail (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS invoice_payment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    invoice_no VARCHAR(50) NOT NULL,
    payment_date DATETIME(6) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    cheque_bank VARCHAR(255) DEFAULT NULL,
    cheque_no VARCHAR(100) DEFAULT NULL,
    cheque_date DATE DEFAULT NULL,
    cheque_branch VARCHAR(255) DEFAULT NULL,
    slip_file_name VARCHAR(255) DEFAULT NULL,
    slip_file_url VARCHAR(500) DEFAULT NULL,
    receipt_no VARCHAR(50) DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_invoice_payment_invoice_no (invoice_no),
    KEY idx_invoice_payment_payment_date (payment_date),
    CONSTRAINT fk_invoice_payment_invoice FOREIGN KEY (invoice_no) REFERENCES invoice (invoice_no),
    CONSTRAINT fk_invoice_payment_created_by FOREIGN KEY (created_by) REFERENCES user (id),
    CONSTRAINT fk_invoice_payment_updated_by FOREIGN KEY (updated_by) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS invoice_payment_attachment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    invoice_payment_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) DEFAULT NULL,
    file_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) DEFAULT NULL,
    file_size BIGINT DEFAULT NULL,
    sort_order INT DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_invoice_payment_attachment_payment (invoice_payment_id),
    CONSTRAINT fk_invoice_payment_attachment_payment FOREIGN KEY (invoice_payment_id) REFERENCES invoice_payment (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
