CREATE TABLE IF NOT EXISTS purchase_order (
    purchase_order_no VARCHAR(50) NOT NULL,
    sales_order_no VARCHAR(50) NOT NULL,
    supplier_id VARCHAR(50) NOT NULL,
    supplier_shipping_id BIGINT NOT NULL,
    doc_date DATE NOT NULL,
    production_lead_time_day INT DEFAULT NULL,
    shipping_lead_time_day INT DEFAULT NULL,
    status VARCHAR(30) NOT NULL,
    currency VARCHAR(10) DEFAULT NULL,
    exchange_rate DECIMAL(18,4) DEFAULT NULL,
    sub_total DECIMAL(18,2) DEFAULT NULL,
    sub_total_thb DECIMAL(18,2) DEFAULT NULL,
    grand_total DECIMAL(18,2) DEFAULT NULL,
    grand_total_thb DECIMAL(18,2) DEFAULT NULL,
    remark VARCHAR(2000) DEFAULT NULL,
    rev_no INT DEFAULT NULL,
    supplier_name_snapshot VARCHAR(255) DEFAULT NULL,
    supplier_address_snapshot VARCHAR(2000) DEFAULT NULL,
    supplier_contact_snapshot VARCHAR(255) DEFAULT NULL,
    supplier_phone_snapshot VARCHAR(100) DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (purchase_order_no),
    KEY idx_purchase_order_sales_order_no (sales_order_no),
    KEY idx_purchase_order_supplier_id (supplier_id),
    KEY idx_purchase_order_supplier_shipping_id (supplier_shipping_id),
    KEY idx_purchase_order_doc_date (doc_date),
    KEY idx_purchase_order_status (status),
    CONSTRAINT fk_purchase_order_sales_order FOREIGN KEY (sales_order_no) REFERENCES sales_order (sales_order_no),
    CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id),
    CONSTRAINT fk_purchase_order_supplier_shipping FOREIGN KEY (supplier_shipping_id) REFERENCES supplier_shipping (id),
    CONSTRAINT fk_purchase_order_created_by FOREIGN KEY (created_by) REFERENCES user (id),
    CONSTRAINT fk_purchase_order_updated_by FOREIGN KEY (updated_by) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS purchase_order_detail (
    id BIGINT NOT NULL AUTO_INCREMENT,
    purchase_order_no VARCHAR(50) NOT NULL,
    sales_order_detail_id BIGINT DEFAULT NULL,
    line_no INT DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    type VARCHAR(255) DEFAULT NULL,
    capacity VARCHAR(255) DEFAULT NULL,
    size VARCHAR(255) DEFAULT NULL,
    spec VARCHAR(2000) DEFAULT NULL,
    quantity DECIMAL(18,2) DEFAULT NULL,
    supplier_currency VARCHAR(10) DEFAULT NULL,
    supplier_unit_price DECIMAL(18,4) DEFAULT NULL,
    exchange_rate DECIMAL(18,4) DEFAULT NULL,
    supplier_shipping_cost DECIMAL(18,4) DEFAULT NULL,
    supplier_total_unit_cost DECIMAL(18,4) DEFAULT NULL,
    amount_supplier_currency DECIMAL(18,2) DEFAULT NULL,
    amount_thb DECIMAL(18,2) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    rfq_detail_id BIGINT DEFAULT NULL,
    rfq_tier_id BIGINT DEFAULT NULL,
    quotation_detail_id BIGINT DEFAULT NULL,
    shipping_method VARCHAR(10) DEFAULT NULL,
    supplier_quote_tier_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_purchase_order_detail_po_no (purchase_order_no),
    KEY idx_purchase_order_detail_sales_order_detail_id (sales_order_detail_id),
    CONSTRAINT fk_purchase_order_detail_po FOREIGN KEY (purchase_order_no) REFERENCES purchase_order (purchase_order_no),
    CONSTRAINT fk_purchase_order_detail_sales_order_detail FOREIGN KEY (sales_order_detail_id) REFERENCES sales_order_detail (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS purchase_order_attachment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    purchase_order_no VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) DEFAULT NULL,
    file_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) DEFAULT NULL,
    file_size BIGINT DEFAULT NULL,
    remark VARCHAR(1000) DEFAULT NULL,
    sort_order INT DEFAULT NULL,
    active BIT(1) NOT NULL DEFAULT b'1',
    created_by VARCHAR(255) DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_purchase_order_attachment_po_no (purchase_order_no),
    CONSTRAINT fk_purchase_order_attachment_po FOREIGN KEY (purchase_order_no) REFERENCES purchase_order (purchase_order_no),
    CONSTRAINT fk_purchase_order_attachment_created_by FOREIGN KEY (created_by) REFERENCES user (id),
    CONSTRAINT fk_purchase_order_attachment_updated_by FOREIGN KEY (updated_by) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
