CREATE TABLE IF NOT EXISTS receipt (
    receipt_no VARCHAR(50) NOT NULL,
    receipt_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    invoice_no VARCHAR(50) NOT NULL,
    invoice_payment_id BIGINT NOT NULL,
    sales_order_no VARCHAR(50) DEFAULT NULL,
    quotation_no VARCHAR(50) DEFAULT NULL,
    doc_date DATE NOT NULL,
    paid_date DATETIME(6) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    customer_id VARCHAR(100) DEFAULT NULL,
    customer_address_id BIGINT DEFAULT NULL,
    customer_contact_id BIGINT DEFAULT NULL,
    sales_id VARCHAR(50) DEFAULT NULL,
    co_sales_id VARCHAR(20) DEFAULT NULL,
    subtotal DECIMAL(18,2) DEFAULT NULL,
    discount DECIMAL(18,2) DEFAULT NULL,
    amount DECIMAL(18,2) DEFAULT NULL,
    vat_rate DECIMAL(10,4) DEFAULT NULL,
    vat DECIMAL(18,2) DEFAULT NULL,
    grand_total DECIMAL(18,2) DEFAULT NULL,
    payment_method VARCHAR(30) NOT NULL,
    cheque_bank VARCHAR(255) DEFAULT NULL,
    cheque_no VARCHAR(100) DEFAULT NULL,
    cheque_date DATE DEFAULT NULL,
    cheque_branch VARCHAR(255) DEFAULT NULL,
    slip_file_name VARCHAR(255) DEFAULT NULL,
    slip_file_url VARCHAR(500) DEFAULT NULL,
    remark VARCHAR(2000) DEFAULT NULL,
    rev_no INT DEFAULT NULL,
    customer_name_snapshot VARCHAR(255) DEFAULT NULL,
    customer_tax_id_snapshot VARCHAR(50) DEFAULT NULL,
    customer_address_snapshot VARCHAR(2000) DEFAULT NULL,
    customer_contact_snapshot VARCHAR(255) DEFAULT NULL,
    customer_phone_snapshot VARCHAR(100) DEFAULT NULL,
    sales_name_snapshot VARCHAR(255) DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,
    updated_by VARCHAR(255) DEFAULT NULL,
    created_date DATETIME(6) DEFAULT NULL,
    updated_date DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (receipt_no),
    KEY idx_receipt_invoice_no (invoice_no),
    KEY idx_receipt_invoice_payment_id (invoice_payment_id),
    KEY idx_receipt_sales_order_no (sales_order_no),
    KEY idx_receipt_doc_date (doc_date),
    KEY idx_receipt_status (status),
    CONSTRAINT fk_receipt_invoice FOREIGN KEY (invoice_no) REFERENCES invoice (invoice_no),
    CONSTRAINT fk_receipt_invoice_payment FOREIGN KEY (invoice_payment_id) REFERENCES invoice_payment (id),
    CONSTRAINT fk_receipt_sales_order FOREIGN KEY (sales_order_no) REFERENCES sales_order (sales_order_no),
    CONSTRAINT fk_receipt_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_receipt_customer_address FOREIGN KEY (customer_address_id) REFERENCES customer_address (id),
    CONSTRAINT fk_receipt_customer_contact FOREIGN KEY (customer_contact_id) REFERENCES customer_contact (id),
    CONSTRAINT fk_receipt_sales FOREIGN KEY (sales_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_receipt_created_by FOREIGN KEY (created_by) REFERENCES user (id),
    CONSTRAINT fk_receipt_updated_by FOREIGN KEY (updated_by) REFERENCES user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS receipt_detail (
    id BIGINT NOT NULL AUTO_INCREMENT,
    receipt_no VARCHAR(50) NOT NULL,
    invoice_detail_id BIGINT DEFAULT NULL,
    line_no INT DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    type VARCHAR(255) DEFAULT NULL,
    capacity VARCHAR(255) DEFAULT NULL,
    size VARCHAR(255) DEFAULT NULL,
    spec VARCHAR(2000) DEFAULT NULL,
    unit_price DECIMAL(18,2) DEFAULT NULL,
    quantity DECIMAL(18,2) DEFAULT NULL,
    amount DECIMAL(18,2) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_receipt_detail_receipt_no (receipt_no),
    KEY idx_receipt_detail_invoice_detail_id (invoice_detail_id),
    CONSTRAINT fk_receipt_detail_receipt FOREIGN KEY (receipt_no) REFERENCES receipt (receipt_no),
    CONSTRAINT fk_receipt_detail_invoice_detail FOREIGN KEY (invoice_detail_id) REFERENCES invoice_detail (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
